site_name: CPS HHBK Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Actors:
      - LED: actors/led.md
  - Sensors:
      - KY001: sensors/sensor-KY001.md
