site_name: CPS HHBK Documentation
theme:
  name: mkdocs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Actuators:
      - Overview: actuators/index.md
      - Actuator A: actuators/actuator_a.md
      - Actuator B: actuators/actuator_b.md
  - Sensors:
      - Overview: sensors/index.md
      - Sensor A: sensors/sensor_a.md
      - Sensor B: sensors/sensor_b.md
